export const SITE_URL = "https://imageresizelab.com";
export const SITE_NAME = "ImageResizeLab";

export const NAV_GROUPS = [
  {
    label: "Resize",
    href: "/",
    items: [
      { href: "/", label: "Image resizer", blurb: "Pixels, percent, or max side" },
      { href: "/social-media-image-resizer", label: "Social media sizes", blurb: "Instagram, YouTube, X, LinkedIn" },
      { href: "/image-cropper", label: "Image cropper", blurb: "Free crop or locked aspect" },
      { href: "/bulk-image-resizer", label: "Bulk resizer", blurb: "Many files, one size" },
      { href: "/profile-picture-resizer", label: "Profile picture", blurb: "Square crop for avatars" },
    ],
  },
  {
    label: "Compress",
    href: "/jpg-compressor",
    items: [
      { href: "/jpg-compressor", label: "JPG compressor", blurb: "Quality slider, smaller JPEGs" },
      { href: "/png-compressor", label: "PNG compressor", blurb: "Shrink PNG or switch format" },
      { href: "/compress-image-to-size", label: "Compress to size", blurb: "Hit a target in KB" },
      { href: "/webp-converter", label: "WebP converter", blurb: "Modern format, smaller files" },
    ],
  },
  {
    label: "Convert",
    href: "/png-to-jpg",
    items: [
      { href: "/jpg-to-png", label: "JPG → PNG", blurb: "JPEG into a PNG" },
      { href: "/png-to-jpg", label: "PNG → JPG", blurb: "Flatten transparency" },
      { href: "/webp-to-jpg", label: "WebP → JPG", blurb: "WebP into a JPEG" },
      { href: "/jpg-to-webp", label: "JPG → WebP", blurb: "JPEG into WebP" },
      { href: "/png-to-webp", label: "PNG → WebP", blurb: "PNG into WebP" },
      { href: "/webp-to-png", label: "WebP → PNG", blurb: "Keep transparency" },
      { href: "/svg-to-png", label: "SVG → PNG", blurb: "Vector to raster" },
    ],
  },
  {
    label: "Inspect",
    href: "/image-dimension-checker",
    items: [
      { href: "/image-dimension-checker", label: "Dimension checker", blurb: "Width, height, megapixels" },
      { href: "/exif-viewer", label: "EXIF viewer", blurb: "Camera, GPS, dates" },
      { href: "/remove-exif", label: "Remove EXIF", blurb: "Strip metadata" },
      { href: "/image-to-base64", label: "Image to Base64", blurb: "Data URI for CSS or HTML" },
      { href: "/base64-to-image", label: "Base64 to image", blurb: "Paste and download" },
      { href: "/image-color-picker", label: "Color picker", blurb: "Click a pixel for hex" },
    ],
  },
  {
    label: "Make",
    href: "/favicon-generator",
    items: [
      { href: "/favicon-generator", label: "Favicon generator", blurb: "ICO plus PNG sizes" },
      { href: "/watermark-image", label: "Watermark", blurb: "Text over a photo" },
      { href: "/round-image", label: "Round image", blurb: "Circle crop, transparent PNG" },
      { href: "/rotate-image", label: "Rotate & flip", blurb: "90°, 180°, mirror" },
      { href: "/passport-photo-maker", label: "Passport photo", blurb: "2×2 in and 35×45 mm" },
      { href: "/add-image-border", label: "Add border", blurb: "Solid frame around a photo" },
      { href: "/grayscale-image", label: "Grayscale", blurb: "Black and white" },
      { href: "/blur-image", label: "Blur image", blurb: "Soft-focus a photo" },
      { href: "/placeholder-image", label: "Placeholder", blurb: "Solid canvas with size text" },
    ],
  },
] as const;

export const ALL_TOOLS = [
  { href: "/", title: "Image resizer", blurb: "Resize by pixels, percent, or longest side. JPEG, PNG, or WebP out.", tag: "Resize" },
  { href: "/jpg-compressor", title: "JPG compressor", blurb: "Shrink JPEGs with a quality slider. Stays in your browser.", tag: "Compress" },
  { href: "/png-compressor", title: "PNG compressor", blurb: "Reduce PNG size by scaling or converting to WebP or JPG.", tag: "Compress" },
  { href: "/webp-converter", title: "WebP converter", blurb: "Turn JPG, PNG, or GIF into a smaller WebP file.", tag: "Convert" },
  { href: "/jpg-to-png", title: "JPG to PNG", blurb: "Convert a JPEG into a lossless PNG.", tag: "Convert" },
  { href: "/png-to-jpg", title: "PNG to JPG", blurb: "Flatten a PNG onto a background and save as JPEG.", tag: "Convert" },
  { href: "/webp-to-jpg", title: "WebP to JPG", blurb: "Convert a WebP image into a JPEG.", tag: "Convert" },
  { href: "/jpg-to-webp", title: "JPG to WebP", blurb: "Re-encode a JPEG as WebP.", tag: "Convert" },
  { href: "/png-to-webp", title: "PNG to WebP", blurb: "Convert a PNG to WebP, transparency kept when the browser allows.", tag: "Convert" },
  { href: "/webp-to-png", title: "WebP to PNG", blurb: "Convert a WebP image into a PNG.", tag: "Convert" },
  { href: "/image-cropper", title: "Image cropper", blurb: "Crop freehand or lock 1:1, 4:3, 16:9, 9:16.", tag: "Resize" },
  { href: "/image-dimension-checker", title: "Image dimension checker", blurb: "Read width, height, aspect ratio, type, and file size.", tag: "Inspect" },
  { href: "/image-to-base64", title: "Image to Base64", blurb: "Encode a photo as a data URI or raw Base64.", tag: "Inspect" },
  { href: "/base64-to-image", title: "Base64 to image", blurb: "Paste Base64 or a data URI and download the picture.", tag: "Inspect" },
  { href: "/exif-viewer", title: "EXIF viewer", blurb: "Camera make, date, GPS, and orientation from a JPEG.", tag: "Inspect" },
  { href: "/favicon-generator", title: "Favicon generator", blurb: "Build 16, 32, 48, 180, 192, 512 PNGs plus an ICO.", tag: "Make" },
  { href: "/social-media-image-resizer", title: "Social media image resizer", blurb: "Instagram, YouTube, Facebook, X, LinkedIn, and Pinterest sizes.", tag: "Resize" },
  { href: "/bulk-image-resizer", title: "Bulk image resizer", blurb: "Resize a batch of photos to one width or height.", tag: "Resize" },
  { href: "/compress-image-to-size", title: "Compress image to size", blurb: "Binary-search JPEG/WebP quality until you hit a KB target.", tag: "Compress" },
  { href: "/remove-exif", title: "Remove EXIF", blurb: "Re-encode so camera and GPS tags are gone.", tag: "Inspect" },
  { href: "/image-color-picker", title: "Image color picker", blurb: "Click a pixel and copy hex or RGB.", tag: "Inspect" },
  { href: "/round-image", title: "Round image", blurb: "Circle crop with a transparent PNG.", tag: "Make" },
  { href: "/rotate-image", title: "Rotate image", blurb: "Turn 90°, 180°, or flip horizontal and vertical.", tag: "Make" },
  { href: "/watermark-image", title: "Watermark image", blurb: "Stamp text on a photo — position, size, opacity.", tag: "Make" },
  { href: "/passport-photo-maker", title: "Passport photo maker", blurb: "US 2×2 in or 35×45 mm with a white or colored background.", tag: "Make" },
  { href: "/profile-picture-resizer", title: "Profile picture resizer", blurb: "Square crop for avatars at 400×400 or 800×800.", tag: "Resize" },
  { href: "/add-image-border", title: "Add image border", blurb: "A solid frame in any color and thickness.", tag: "Make" },
  { href: "/grayscale-image", title: "Grayscale image", blurb: "Convert a photo to black and white.", tag: "Make" },
  { href: "/blur-image", title: "Blur image", blurb: "Gaussian-style blur for backgrounds or privacy.", tag: "Make" },
  { href: "/svg-to-png", title: "SVG to PNG", blurb: "Rasterize an SVG at a chosen width.", tag: "Convert" },
  { href: "/placeholder-image", title: "Placeholder image", blurb: "Generate a colored rectangle with dimensions on it.", tag: "Make" },
] as const;
